title: Oskoreia
description: Star Citizen Organisation
baseurl: ""
url: "https://oskoreia.org"
collections:
  pages:
    output: true
    permalink: /:name/
  ships:
    output: true
    permalink: /ships/:name.html

